import json


class AuthSource(object):
    """ Enum listing all authentication sources we currently support. """
    DUMMY = "fake_auth_source"
    GOOGLE_PLUS = "google_plus"
    FACEBOOK = "facebook"


class Model(object):

    def __init__(self):
        pass

    def __init__(self, **entries):
        """
        Reconstructs a Model instance from a dict.  Useful when deserializing.
        Uses code from:
        http://stackoverflow.com/questions/1305532/convert-python-dict-to-object
        """
        self.__dict__.update(entries)

    def to_json(self):
        return json.dumps(self.__dict__)


class User(Model):
    user_id = None  # generated by DB
    username = None
    auth_source = None
    auth_source_id = None

class Category(Model):
    cat_id = None # generated by DB
    name = None
    creator_id = None

class Item(Model):
    item_id = None # generated by DB
    name = None
    cat_id = None
    creator_id = None
